### ISSUE TITLE
Publish new version of package

### ISSUE THREAD

**Issue by Ginden** [cmrigney/fast-xml2js#11]
Issue #10 was fixed in commit 65b235b04eb0af386f61c59b4fb50063142a1653 (1 Aug 2017), but last release of package was on 2016-04-15T16:20:32.503Z.

**Comment by cmrigney** [comment]
Thanks, I'll try to get this published later today.

**Comment by cmrigney** [comment]
@Ginden Published as 1.08! Let me know if that works.  It's been so long, I'm having trouble building it locally without installing certain build tools first.
